    - name: Checkout @TPL:product;_@TPL:hw; @TPL:submodule;
      executionOrder: 0
      failAbortsPipeline: false
      steps:
      - call: Repository.prepareGitRepo
      - cmd: if not [@TPL:submodule;] == [] (git checkout origin/develop)
        fromPath: @TPL:submodule;
        name: checkout @TPL:submodule; develop
      
      
        
        
