    - name: Make Build @TPL:product;_@TPL:hw;
      description: Build @TPL:product;_@TPL:hw; with CMake build
      executionOrder: 2
      steps:
      - name: Make
        cmd: 01_make.bat @TPL:product;_@TPL:hw; @ENV:BUILD_NUMBER; @ENV:JOB_NAME;
        fromPath: apl_gac\tools\builder\cmake
      archive:
      - backend: jenkins
        includes: \*.*
        fromPath: generatedFiles\@TPL:product;_@TPL:hw;\exec
        zip: true
        zipName: Executables_@ENV:BUILD_NUMBER;.zip
      - backend: jenkins
        includes: \*.*
        fromPath: generatedFiles\@TPL:product;_@TPL:hw;\log
        zip: true
        zipName: Log_@ENV:BUILD_NUMBER;.zip