    - name: CMake Build @TPL:product;_@TPL:hw;
      description: Build @TPL:product;_@TPL:hw; with CMake build
      executionOrder: 1
      steps:
      - cmd: generate_scom.bat
        fromPath: apl_gac\tools\builder\
        #to create build_version_info.c file
      - cmd: build_apl_gac.bat
        fromPath: apl_gac\tools\builder
      - name: Cmake
        cmd: 00_Cmake.bat @TPL:product;_@TPL:hw; @ENV:BUILD_NUMBER; @ENV:JOB_NAME;
        fromPath: apl_gac\tools\builder\cmake