    - name: Checkout @TPL:product;_@TPL:hw; @TPL:submodule;
      executionOrder: 0
      failAbortsPipeline: false
      steps:
      - cmd: git clone "ssh://git@sourcecode.socialcoding.bosch.com:7999/dasygaca18/dasy_gaca18_cmp_fork.git" -b @PARAM:BRANCH; --recursive .
      - cmd: git fetch -p origin @PARAM:BRANCH;
      - cmd: git checkout -f @PARAM:BRANCH;
      - cmd: git pull origin @PARAM:BRANCH;
      - cmd: git submodule sync --recursive 
      - cmd: git submodule update --init --recursive --force 
      - cmd: git submodule foreach --recursive git reset --hard HEAD 
      - cmd: git submodule foreach --recursive git clean -xffd    
