    - name: ReleaseContainer @TPL:product;_@TPL:hw;
      description: Build @TPL:product;_@TPL:hw; with CMake build
      executionOrder: 1
      steps:
      - name: Generate SCOM
        cmd: generate_scom.bat
        fromPath: apl_gac\tools\builder
      - name: Build Tool
        cmd: build_apl_gac.bat
        fromPath: apl_gac\tools\builder
      - name: Cmake
        cmd: 00_Cmake.bat @TPL:product;_@TPL:hw; @ENV:BUILD_NUMBER; @ENV:JOB_NAME;
        fromPath: apl_gac\tools\builder\cmake
      - name: Make
        cmd: 01_make.bat @TPL:product;_@TPL:hw; @ENV:BUILD_NUMBER; @ENV:JOB_NAME;
        fromPath: apl_gac\tools\builder\cmake
      - name: Release_Container
        cmd: Create_Archive_customer_release.bat @TPL:product;_@TPL:hw; Release_GAC
        fromPath: jenkins\customerReleaseContainer
      archive:
      - backend: jenkins
        includes: \**
        fromPath: build_cmake\@TPL:product;_@TPL:hw;\release\Release_GAC
        zip: true
        zipName: GAC_CustomerReleaseContainer.zip