  - description: Check PR
    executionOrder: 0
    label: windows
    stages:
    - name: Check PR
      executionOrder: 0
      runIfEnvIsSet: IS_PULL_REQUEST_JOB
      skipIfEnvIsSet: PR_CHECKED
      steps:
      #- call: Workspace.setEnvVar
      #  args:
      #    name: PR_CHECKED
      #- call: PullRequest.addReviewersWithCodeOwnersFile
      #- call: PullRequest.checkSubmodules
      #- call: PullRequest.addSpecialReviewers
      #  args:
      #    name: CI Maintainers
      #    required: true
      #    pattern:
      #    - '/jenkins/** @ @'

